===================================================
Doctest for 7-base_geometry.py
===================================================

Import module
----------------------------
	>>> BaseGeometry = __import__('7-base_geometry').BaseGeometry
	
Check for equality of ids of two instances
----------------------------------------------
	>>> bg1 = BaseGeometry()
	>>> bg2 = BaseGeometry()
	>>> id(bg1) == id(bg2)
	False

Check for argument passing
---------------------------------------------
	>>> bg1 = BaseGeometry(2)
	Traceback (most recent call last):
		...
	TypeError: BaseGeometry() takes no arguments

	>>> bg1 = BaseGeometry("string")
	Traceback (most recent call last):
		...
	TypeError: BaseGeometry() takes no arguments

	>>> bg1 = BaseGeometry(True)
	Traceback (most recent call last):
		...
	TypeError: BaseGeometry() takes no arguments

Test for method `area`
------------------------------------
	>>> bg1 = BaseGeometry()
	>>> bg1.area()
	Traceback (most recent call last):
		...
	Exception: area() is not implemented
	>>> bg1.area(1)
	Traceback (most recent call last):
		...
	TypeError: area() takes 1 positional argument but 2 were given

Test for method `integer_validator`
-----------------------------------------
	>>> bg1 = BaseGeometry()
	>>> bg1.integer_validator("name", "John")
	Traceback (most recent call last):
		...
	TypeError: name must be an integer

	>>> bg1.integer_validator("age", 0)
	Traceback (most recent call last):
		...
	ValueError: age must be greater than 0
	
	>>> bg1.integer_validator("distance", -4)
	Traceback (most recent call last):
		...
	ValueError: distance must be greater than 0

	>>> bg1.integer_validator("distance", (1, 3))
	Traceback (most recent call last):
		...
	TypeError: distance must be an integer

	>>> bg1.integer_validator("distance", [1, 3])
	Traceback (most recent call last):
		...
	TypeError: distance must be an integer

	>>> bg1.integer_validator("my_int", 12)

	>>> bg1.integer_validator()
	Traceback (most recent call last):
		...
	TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

	>>> bg1.integer_validator(12)
	Traceback (most recent call last):
		...
	TypeError: integer_validator() missing 1 required positional argument: 'value'
	>>> bg1.integer_validator("integer", 1, 2)
	Traceback (most recent call last):
		...
	TypeError: integer_validator() takes 3 positional arguments but 4 were given

Print the object
------------------------
	>>> bg1 #doctest: +ELLIPSIS
	<7-base_geometry.BaseGeometry object at 0x...>
	>>> print(bg1) #doctest: +ELLIPSIS
	<7-base_geometry.BaseGeometry object at 0x...>
